name: Build binaries on new tag and create a release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.13"
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - run: GOOS=windows GOARCH=amd64 ; go build -o build/goira-${{steps.vars.outputs.tag}}+${GOOS}-${GOARCH}.exe
      - run: GOOS=darwin GOARCH=amd64 ; go build -o build/goira-${{steps.vars.outputs.tag}}+${GOOS}-${GOARCH}
      - run: GOOS=darwin GOARCH=arm64 ; go build -o build/goira-${{steps.vars.outputs.tag}}+${GOOS}-${GOARCH}
      - run: GOOS=linux GOARCH=amd64 ; go build -o build/goira-${{steps.vars.outputs.tag}}+${GOOS}-${GOARCH}
      - run: GOOS=linux GOARCH=arm ; go build -o build/goira-${{steps.vars.outputs.tag}}+${GOOS}-${GOARCH}
      - run: GOOS=linux GOARCH=arm64 ; go build -o build/goira-${{steps.vars.outputs.tag}}+${GOOS}-${GOARCH}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          tag: ${{ steps.vars.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
